version: '3'
services:
 spark_container:
   user: root
   image: jupyter/pyspark-notebook
   working_dir: /opt/dna-spark/
   ports:
     - 8888:8888
     - 4040:4040
   volumes:
     - .:/opt/dna-spark/
   entrypoint: ./docker-entrypoint.sh
   command: jupyter
