config:
  configBucket: dna_workshop_spark
  gceClusterConfig:
    serviceAccountScopes:
      - https://www.googleapis.com/auth/bigquery
      - https://www.googleapis.com/auth/bigtable.admin.table
      - https://www.googleapis.com/auth/bigtable.data
      - https://www.googleapis.com/auth/cloud.useraccounts.readonly
      - https://www.googleapis.com/auth/devstorage.full_control
      - https://www.googleapis.com/auth/devstorage.read_write
      - https://www.googleapis.com/auth/logging.write
    subnetworkUri: https://www.googleapis.com/compute/v1/projects/dxtdna/regions/us-central1/subnetworks/default
    zoneUri: https://www.googleapis.com/compute/v1/projects/dxtdna/zones/us-central1-c
  masterConfig:
    numInstances: 1
    minCpuPlatform: AUTOMATIC
    preemptibility: NON_PREEMPTIBLE
    imageUri: https://www.googleapis.com/compute/v1/projects/cloud-dataproc/global/images/dataproc-2-0-ubu18-20200813-120433-rc01
    machineTypeUri: https://www.googleapis.com/compute/v1/projects/dxtdna/zones/us-central1-c/machineTypes/n1-standard-4
    diskConfig:
      bootDiskSizeGb: 500
      bootDiskType: pd-standard
  workerConfig:
    numInstances: 2
    preemptibility: NON_PREEMPTIBLE
    imageUri: https://www.googleapis.com/compute/v1/projects/cloud-dataproc/global/images/dataproc-2-0-ubu18-20200813-120433-rc01
    machineTypeUri: https://www.googleapis.com/compute/v1/projects/dxtdna/zones/us-central1-c/machineTypes/n1-standard-2
    minCpuPlatform: AUTOMATIC
    diskConfig:
      bootDiskSizeGb: 500
      bootDiskType: pd-standard
  secondaryWorkerConfig:
    numInstances: 4
    minCpuPlatform: AUTOMATIC
    preemptibility: PREEMPTIBLE
    imageUri: https://www.googleapis.com/compute/v1/projects/cloud-dataproc/global/images/dataproc-2-0-ubu18-20200813-120433-rc01
    machineTypeUri: https://www.googleapis.com/compute/v1/projects/dxtdna/zones/us-central1-c/machineTypes/n1-standard-2
    diskConfig:
      bootDiskSizeGb: 100
      bootDiskType: pd-standard
  softwareConfig:
    imageVersion: 2.0.0-RC9-ubuntu18
    optionalComponents:
    - JUPYTER
    - ANACONDA
    properties:
      capacity-scheduler:yarn.scheduler.capacity.root.default.ordering-policy: fair
      core:fs.gs.block.size: '134217728'
      core:fs.gs.metadata.cache.enable: 'false'
      core:hadoop.ssl.enabled.protocols: TLSv1,TLSv1.1,TLSv1.2
      distcp:mapreduce.map.java.opts: -Xmx576m
      distcp:mapreduce.map.memory.mb: '768'
      distcp:mapreduce.reduce.java.opts: -Xmx576m
      distcp:mapreduce.reduce.memory.mb: '768'
      hdfs:dfs.datanode.address: 0.0.0.0:9866
      hdfs:dfs.datanode.http.address: 0.0.0.0:9864
      hdfs:dfs.datanode.https.address: 0.0.0.0:9865
      hdfs:dfs.datanode.ipc.address: 0.0.0.0:9867
      hdfs:dfs.namenode.handler.count: '60'
      hdfs:dfs.namenode.http-address: 0.0.0.0:9870
      hdfs:dfs.namenode.https-address: 0.0.0.0:9871
      hdfs:dfs.namenode.secondary.http-address: 0.0.0.0:9868
      hdfs:dfs.namenode.secondary.https-address: 0.0.0.0:9869
      hdfs:dfs.namenode.service.handler.count: '30'
      hive:hive.fetch.task.conversion: none
      mapred-env:HADOOP_JOB_HISTORYSERVER_HEAPSIZE: '3840'
      mapred:mapreduce.job.maps: '51'
      mapred:mapreduce.job.reduce.slowstart.completedmaps: '0.95'
      mapred:mapreduce.job.reduces: '17'
      mapred:mapreduce.jobhistory.recovery.store.class: org.apache.hadoop.mapreduce.v2.hs.HistoryServerLeveldbStateStoreService
      mapred:mapreduce.map.cpu.vcores: '1'
      mapred:mapreduce.map.java.opts: -Xmx1638m
      mapred:mapreduce.map.memory.mb: '2048'
      mapred:mapreduce.reduce.cpu.vcores: '1'
      mapred:mapreduce.reduce.java.opts: -Xmx1638m
      mapred:mapreduce.reduce.memory.mb: '2048'
      mapred:mapreduce.task.io.sort.mb: '256'
      mapred:yarn.app.mapreduce.am.command-opts: -Xmx1638m
      mapred:yarn.app.mapreduce.am.resource.cpu-vcores: '1'
      mapred:yarn.app.mapreduce.am.resource.mb: '2048'
      spark-env:SPARK_DAEMON_MEMORY: 3840m
      spark:spark.driver.maxResultSize: 1920m
      spark:spark.driver.memory: 3840m
      spark:spark.executor.cores: '1'
      spark:spark.executor.instances: '2'
      spark:spark.executor.memory: 2688m
      spark:spark.executorEnv.OPENBLAS_NUM_THREADS: '1'
      spark:spark.scheduler.mode: FAIR
      spark:spark.sql.cbo.enabled: 'true'
      spark:spark.ui.port: '0'
      spark:spark.yarn.am.memory: 640m
      yarn-env:YARN_NODEMANAGER_HEAPSIZE: '1920'
      yarn-env:YARN_RESOURCEMANAGER_HEAPSIZE: '3840'
      yarn-env:YARN_TIMELINESERVER_HEAPSIZE: '3840'
      yarn:yarn.nodemanager.address: 0.0.0.0:8026
      yarn:yarn.nodemanager.resource.memory-mb: '6144'
      yarn:yarn.resourcemanager.nodemanager-graceful-decommission-timeout-secs: '86400'
      yarn:yarn.scheduler.maximum-allocation-mb: '6144'
      yarn:yarn.scheduler.minimum-allocation-mb: '512'
  endpointConfig:
    enableHttpPortAccess: true
    httpPorts:
      HDFS NameNode: https://vl5ofogf2fbypp4iugf6vo3e2m-dot-us-central1.dataproc.googleusercontent.com/hdfs/dfshealth.html
      Jupyter: https://vl5ofogf2fbypp4iugf6vo3e2m-dot-us-central1.dataproc.googleusercontent.com/jupyter/
      JupyterLab: https://vl5ofogf2fbypp4iugf6vo3e2m-dot-us-central1.dataproc.googleusercontent.com/jupyter/lab/
      MapReduce Job History: https://vl5ofogf2fbypp4iugf6vo3e2m-dot-us-central1.dataproc.googleusercontent.com/jobhistory/
      Spark History Server: https://vl5ofogf2fbypp4iugf6vo3e2m-dot-us-central1.dataproc.googleusercontent.com/sparkhistory/
      Tez: https://vl5ofogf2fbypp4iugf6vo3e2m-dot-us-central1.dataproc.googleusercontent.com/apphistory/tez-ui/
      YARN Application Timeline: https://vl5ofogf2fbypp4iugf6vo3e2m-dot-us-central1.dataproc.googleusercontent.com/apphistory/
      YARN ResourceManager: https://vl5ofogf2fbypp4iugf6vo3e2m-dot-us-central1.dataproc.googleusercontent.com/yarn/
