lakes:
  transient: 'file:///datalake/transient'
  raw: 'file:///datalake/raw'
  trusted: 'file:///datalake/trusted'
  refined: 'file:///datalake/refined'
  models: 'file:///datalake/models'
  backup: 'file:///datalake/backup'
  secrets: 'file:///datalake/secrets'
  config: 'file:///home/jovyan/dna'
